project:
  type: website
  output-dir: docs
website:
  title: "UCD-SeRG"
  repo-url: https://github.com/UCD-SERG/ucd-serg.github.io
  repo-actions: [edit, source, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: opportunities.qmd
        text: Opportunities

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

editor: source

