project:
  type: website
  output-dir: docs
website:
  title: "UCD-SeRG"
  repo-url: https://github.com/UCD-SERG/ucd-serg.github.io
  repo-actions: [edit, source, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: opportunities.qmd
        text: Opportunities
      - href: lab-manual/index.qmd
        text: Lab Manual
  sidebar:
    - id: lab-manual
      title: "Lab Manual"
      style: "docked"
      collapse-level: 1
      contents:
        - lab-manual/index.qmd
        - lab-manual/culture-and-conduct.qmd
        - lab-manual/communication.qmd
        - lab-manual/reproducibility.qmd
        - lab-manual/coding-practices.qmd
        - lab-manual/publications.qmd
        - lab-manual/professional-development.qmd
        - lab-manual/checklists.qmd
        - lab-manual/resources.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

editor: source

